def error(msg):
    raise Exception(msg)
